name: Append-Only Guard

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-append-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check append-only events
        run: ./scripts/check-append-only.sh origin/main
